id: all_tickers_names
namespace: ppt-project
description: |
  Working version for Kestra 0.22.2 (GCP).


concurrency:
  limit: 1


inputs:
  - id: whole_history
    type: BOOLEAN
    defaults: false
  - id: reload_tickers_list
    type: BOOLEAN
    defaults: false
  - id: reload_portfolio
    type: BOOLEAN
    defaults: false
  - id: initialize
    type: BOOLEAN
    defaults: false


variables:
  all_tickers_table: "{{kv('all_tickers_table')}}"
  all_tickers_prices_table: "{{kv('all_tickers_prices_table')}}"


tasks:
  - id: first_time_init
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.initialize == true}}"
    then:
      - id: sync_scripts
        type: io.kestra.plugin.git.SyncNamespaceFiles
        url: https://github.com/mananyev/portfolio-performance-tracking
        branch: "{{kv('BRANCH')}}"
        namespace: "{{flow.namespace}}"
        gitDirectory: src/kestra/scripts
        dryRun: false

      - id: create_all_tickers_prices_table
        type: io.kestra.plugin.gcp.bigquery.Query
        sql: |
          CREATE TABLE IF NOT EXISTS `{{render(vars.all_tickers_prices_table)}}`
          (
              unique_row_id BYTES OPTIONS (description = 'A unique identifier for the ticker-date, generated by hashing ticker and date.')
              , ticker STRING OPTIONS (description = 'The ticker symbol from Yahoo! Finance.')
              , date DATE OPTIONS (description = 'The date to which financial data corresponds.')
              , open FLOAT64 OPTIONS (description = 'Daily Open price.')
              , high FLOAT64 OPTIONS (description = 'Daily High price.')
              , low FLOAT64 OPTIONS (description = 'Daily Low price')
              , close FLOAT64 OPTIONS (description = 'Daily Close price.')
              , volume INTEGER OPTIONS (description = 'Daily Traded volume.')
              , dividends FLOAT64 OPTIONS (description = 'Daily Dividends paid.')
              , stock_splits FLOAT64 OPTIONS (description = 'Daily Stock splits.')
          )
          PARTITION BY DATE_TRUNC(date, MONTH)
          CLUSTER BY ticker;

      - id: create_all_tickers_table
        type: io.kestra.plugin.gcp.bigquery.Query
        sql: |
          CREATE TABLE IF NOT EXISTS `{{render(vars.all_tickers_table)}}`
          (
              ticker STRING OPTIONS (description = 'The ticker symbol from Yahoo! Finance.')
              , company STRING OPTIONS (description = 'Company name.')
              , region STRING OPTIONS (description = 'Company region.')
              , sector STRING OPTIONS (description = 'Company sector.')
              , industry STRING OPTIONS (description = 'Company industry.')
              , exchange STRING OPTIONS (description = 'Exchange where the ticker is traded.')
          );

  - id: check_reload_tickers_list
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.reload_tickers_list == true}}"
    then:
      - id: clear_all_tickers_list
        type: io.kestra.plugin.core.kv.Delete
        key: all_tickers
        errorOnMissing: false

      - id: set_all_tickers_kv
        type: io.kestra.plugin.core.kv.Set
        key: all_tickers
        kvType: STRING
        value: ""

      - id: get_constituents_urls
        type: io.kestra.plugin.core.http.Download
        uri: "{{kv('CONSTITUENTS_LINKS')}}"

      - id: split_json
        type: io.kestra.plugin.scripts.python.Script
        containerImage: ghcr.io/kestra-io/pydata:latest  # Pre-built image with Pandas
        inputFiles:
          constituents.json: "{{ outputs.get_constituents_urls.uri }}"
        outputFiles:
          - "constituents_links.csv"
        script: |
          import json
          import pandas as pd
          from kestra import Kestra

          with open("constituents.json", 'r') as file:
              constituents_data = json.load(file)

          constituents_df = pd.DataFrame(constituents_data).T
          constituents_df.index.name = 'region'
          constituents_df.to_csv("constituents_links.csv", index=True)

      - id: upload_to_gcs
        type: io.kestra.plugin.gcp.gcs.Upload
        from: "{{outputs.split_json.outputFiles['constituents_links.csv']}}"
        to: "gs://{{kv('GCP_BUCKET_NAME')}}/index_constituents_and_links.csv"

      - id: read_regions_csv
        type: io.kestra.plugin.serdes.csv.CsvToIon
        from: "{{outputs.split_json.outputFiles['constituents_links.csv']}}"

      - id: loop_over_regions
        description: |
          Historic prices in Ticker batches (with `period='max'` argument).
        type: io.kestra.plugin.core.flow.ForEachItem
        items: "{{outputs.read_regions_csv.uri}}"
        namespace: ppt-project
        flowId: backfill_parent_flow
        inputs:
          region_json: "{{taskrun.items}}"
          reload_tickers_list: "{{inputs.reload_tickers_list}}"
          backfill_all: "{{inputs.whole_history}}"
          data_from: "{{trigger.previous ?? (execution.startDate | dateAdd(-1, 'DAYS'))}}"
          data_to: "{{trigger.date ?? (execution.startDate | dateAdd(-1, 'DAYS'))}}"

    else:
      - id: log_ticker_list_in_KV
        type: io.kestra.plugin.core.log.Log
        message: |
          All tickers are already in KV Store.

    finally:
      - id: check_reload_portfolio
        type: io.kestra.plugin.core.flow.If
        condition: "{{inputs.reload_portfolio == true}}"
        then:
          - id: clear_portfolio
            type: io.kestra.plugin.core.kv.Delete
            key: portfolio_tickers
            errorOnMissing: false

          - id: set_portfolio_tickers_kv
            type: io.kestra.plugin.core.kv.Set
            key: portfolio_tickers
            kvType: STRING
            value: ""

        else:
          - id: log_portfolio_tickets
            type: io.kestra.plugin.core.log.Log
            message: |
              Portfolio tickers are already in KV Store.
        
        finally:
          - id: synchronize_portfolio
            description: |
              Checks if tickers used in portfolio are in the data base.
            type: io.kestra.plugin.core.flow.Subflow
            namespace: ppt-project
            flowId: subflow_synchronize_portfolio
            inputs:
              backfill_all: "{{inputs.whole_history}}"
              data_from: "{{trigger.previous ?? (execution.startDate | dateAdd(-1, 'DAYS'))}}"
              data_to: "{{trigger.date ?? (execution.startDate | dateAdd(-1, 'DAYS'))}}"

      - id: read_all_tickers_list
        type: io.kestra.plugin.core.kv.Get
        key: all_tickers

      - id: no_update_after_backfill
        type: io.kestra.plugin.core.flow.If
        condition: "{{inputs.reload_tickers_list == true}}"
        then:
          - id: no_update_needed
            type: io.kestra.plugin.core.log.Log
            message: |
              All tickers were just back-filled.
        else:
          - id: subflow_update_all_tickers_prices
            type: io.kestra.plugin.core.flow.Subflow
            namespace: ppt-project
            flowId: subflow_ticker_history
            inputs:
              region: all
              tickers: "{{outputs.read_all_tickers_list.value}}"
              backfill_all: false
              data_from: "{{trigger.previous ?? (execution.startDate | dateAdd(-1, 'DAYS'))}}"
              data_to: "{{trigger.date ?? (execution.startDate | dateAdd(-1, 'DAYS'))}}"

      - id: run_dbt
        description: |
          Runs the dbt: `dbt build` by default.
        type: io.kestra.plugin.core.flow.Subflow
        namespace: ppt-project
        flowId: bigquery_dbt
        inputs:
          first_dbt_run: "{{inputs.initialize}}"

      - id: purge_files
        type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
        description: To avoid cluttering your storage, we will remove the downloaded files

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{secret('GCP_SERVICE_ACCOUNT')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"


# since we only need the data to be updated for up to previos working day
# we do not need updates past Saturday (Friday data updated), i.e. Sunday
# and on Monday (there is no Sunday updates).
# we also want to exclude public holidays (US in this case).
triggers:
  - id: on_workdays
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 10 * * *"
    conditions:
      - type: io.kestra.plugin.core.condition.Not
        conditions:
          - type: io.kestra.plugin.core.condition.DayWeek
            dayOfWeek: "MONDAY"
          - type: io.kestra.plugin.core.condition.DayWeek
            dayOfWeek: "SUNDAY"
    stopAfter:
      - FAILED
    disabled: false
