id: all_tickers_names
namespace: ppt-project
description: |
  2do:
    - pulls the list of tickers by market.


concurrency:
  limit: 1


inputs:
  - id: whole_history
    type: BOOLEAN
    defaults: false
  - id: test_run
    type: BOOLEAN
    defaults: true
  - id: reload_tickers_list
    type: BOOLEAN
    defaults: false
  - id: reload_portfolio
    type: BOOLEAN
    defaults: false
  - id: first_dbt_run
    type: BOOLEAN
    defaults: false
  # - id: initialize
  #   type: BOOLEAN
  #   defaults: false
  # - id: portfolio_file
  #   type: FILE
  # - id: tickers_list_links_file
  #   type: FILE
  #   displayName: Select a file with links to Wikipedia pages that contain lists of tickers.


tasks:
  # - id: first_time_init
  #   type: io.kestra.plugin.core.flow.If
  #   condition: "{{ inputs.initialize == true }}"
  #   then:
  #     - id: sync
  #       type: io.kestra.plugin.git.SyncNamespaceFiles
  #       url: https://github.com/mananyev/portfolio-performance-tracking
  #       branch: local/kestra
  #       namespace: "{{ flow.namespace }}"
  #       gitDirectory: src/kestra/scripts
  #       dryRun: false
          
  - id: check_reload_tickers_list
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.reload_tickers_list == true }}"
    then:
      - id: clear_tickers_list
        type: io.kestra.plugin.core.kv.Delete
        key: all_tickers
        errorOnMissing: false

  - id: update_data
    description: |
      Historic prices in Ticker batches (with `period='max'` argument).
    type: io.kestra.plugin.core.flow.Subflow
    namespace: ppt-project
    flowId: backfill_parent_flow
    inputs:
      test_run: "{{ inputs.test_run }}"
      backfill_all: "{{ inputs.whole_history }}"
      backfill_since: "{{ trigger.previous ?? (execution.startDate | dateAdd(-1, 'DAYS')) }}"
      backfill_at: "{{ trigger.date ?? (execution.startDate | dateAdd(-1, 'DAYS')) }}"

  - id: check_reload_portfolio
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.reload_portfolio == true }}"
    then:
      - id: clear_portfolio
        type: io.kestra.plugin.core.kv.Delete
        key: portfolio_tickers
        errorOnMissing: false

  - id: synchronize_portfolio
    description: |
      Checks if tickers used in portfolio are in the data base.
    type: io.kestra.plugin.core.flow.Subflow
    namespace: ppt-project
    flowId: subflow_synchronize_portfolio
    inputs:
      backfill_all: "{{ inputs.whole_history }}"
      backfill_since: "{{ trigger.previous ?? (execution.startDate | dateAdd(-1, 'DAYS')) }}"
      backfill_at: "{{ trigger.date ?? (execution.startDate | dateAdd(-1, 'DAYS')) }}"

  - id: run_dbt
    description: |
      Runs the dbt: `dbt build` by default.
    type: io.kestra.plugin.core.flow.Subflow
    namespace: ppt-project
    flowId: postgres_dbt
    inputs:
      first_dbt_run: "{{ inputs.first_dbt_run }}"


triggers:
  - id: daily_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 10 * * *"
    stopAfter:
      - FAILED
    disabled: false
