version: 1

sources:
  - name: staging
    database: "{{ target.project }}"   # dynamically resolves to GCP project
    schema: "{{ target.dataset }}"     # resolves to the dataset in use

    tables:
      - name: portfolio_positions
      - name: all_tickers_prices
