version: 2

# All staging models
models:
  - name: stg_portfolio_positions
    description: "Position changes."
    columns:
      - name: ticker
        data_type: text
        description: "Ticker symbol."
        tests:
          - not_null
          - relationships:
              to: source('staging', 'portfolio_positions')
              field: ticker
      - name: date
        data_type: date
        description: "Date of the transaction."
        tests:
          - not_null
      - name: volume
        data_type: double precision
        description: |
          Volume of the transaction (in shares).
          Can be positive and negative:
          - Positive means adding the position to the portfolio (buying).
          - Negative means withdrawing the position (selling).
        tests:
          - not_null

  - name: stg_tickers_prices
    description: "Cleaned table with all tickers prices."
    tests:
      - dbt_utils.expression_is_true:
          expression: "close >= 0"
    columns:
      - name: ticker
        data_type: text
        description: "Ticker symbol."
        tests:
          - not_null
          - relationships:
              to: source('staging', 'all_tickers_prices')
              field: ticker
      - name: date
        data_type: date
        description: "Date for which the prices in the row are reported."
        tests:
          - not_null
          - relationships:
              to: source('staging', 'all_tickers_prices')
              field: date
      - name: close
        data_type: double precision
        description: "Close price"
      - name: volume
        data_type: bigint
        description: "Daily traded volume."
      - name: dividends
        data_type: double precision
        description: "Dividends issued on a given date."
      - name: stock_splits
        data_type: real
        description: "Stock splits issued on a given date."

  - name: stg_tickers_returns
    description: "Tickers daily close price with daily (log-)returns."
    tests:
      - dbt_utils.expression_is_true:
          expression: "close >= 0"
    columns:
      - name: ticker
        data_type: text
        description: "Ticker symbol."
        tests:
          - not_null
          - relationships:
              to: ref('stg_tickers_prices')
              field: ticker
      - name: date
        data_type: date
        description: "Date."
        tests:
          - not_null
          - relationships:
              to: ref('stg_tickers_prices')
              field: date
      - name: close
        data_type: double precision
        description: "Close price on a given date."
        tests:
          - not_null
      - name: return
        data_type: double precision
        description: "Ticker's daily return."
      - name: log_return
        data_type: double precision
        description: "Ticker's daily log-return"

  - name: stg_portfolio_returns
    description: "Portfolio components' daily close prices and daily returns."
    tests:
      - dbt_utils.expression_is_true:
          expression: "close >= 0"
    columns:
      - name: date
        data_type: date
        description: "Date for which the portfolio parameters are evaluated."
        tests:
          - not_null
          - relationships:
              to: ref('stg_tickers_prices')
              field: date
      - name: ticker
        data_type: text
        description: "Ticker symbol."
        tests:
          - not_null
          - relationships:
              to: ref('stg_tickers_prices')
              field: ticker
          - relationships:
              to: ref('stg_portfolio_positions')
              field: ticker
      - name: close
        data_type: double precision
        description: "Portfolio ticker's close price for the given date."
        tests:
          - not_null
      - name: return
        data_type: double precision
        description: "Portfolio ticker's daily return."
        tests:
          - not_null
      - name: position
        data_type: double precision
        description: "Total position for the portfolio ticker on a given date."
        tests:
          - not_null
      - name: cash_flow
        data_type: double precision
        description: |
          The amount of cash invested/gained from
          buying/selling an asset on a given date.
        tests:
          - not_null
      - name: market_value
        data_type: double precision
        description: |
          Market value for the asset in portfolio on a given date:
          close price times position.
        tests:
          - not_null
      - name: cost
        data_type: double precision
        description: "Total amount of cash invested in a given ticker."
        tests:
          - not_null