version: 1

sources:
  - name: staging
    # not sure how to pass Kestra KVs to this schema YAML...
    # so, keep it the same as in the 
    database: postgres-ppt
    schema: ppt

    tables:
      - name: portfolio_positions
      - name: all_tickers_prices
