volumes:
  grafana-storage:

networks:
  shared:
    external: true
    name: ppt_project_net

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - shared
    volumes:
      - grafana-storage:/var/lib/grafana
