# version: '3'  # annoying warning
services:
  dbt-ppt-project-postgres:
    build:
      context: .
      target: dbt-postgres
    image: dbt/postgres
    volumes:
      - .:/usr/app
      - ~/.dbt/:/root/.dbt/
    network_mode: host